services:
  app-transaction:
    build:
      context: .
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/db_creditguard
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    volumes:
      - .m2:/root/.m2


  mysql:
    container_name: mysql_db
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=db_creditguard'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'

    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

volumes:
  mysql-volume:

