spring:
  application:
    name: creditguard
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3607/db_creditguard
    username: ${DATABASE_USERNAME:myuser}
    password: ${DATABASE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  threads:
    virtual:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    check-template-location: false

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
      hibernate: error

springdoc:
  api-docs:
    path: /api-docs
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
 app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  encoding: @project.build.sourceEncoding@
  java:
   version: @java.version@


